# Project information
site_name: 'sciebo@Learnweb'
site_author: 'Lukas Biermann, Nina Herrmann, Wladislaw Iwanzow, Dennis Meis, Jonathan Neugebauer'
repo_url: "https://github.com/pssl16"

# Copyright
copyright: 'Copyright &copy; 2016 PSSL16'

# Documentation and theme
docs_dir: 'docs'
theme_dir: 'cinder'

pages:
  - Home: 'index.md'
  - ownCloud:
    - Technische Umsetzung: 'owncloud/technische-umsetzung.md'
    - Benutzung: 'owncloud/benutzung.md'
  - Moodle:
    - Technische Umsetzung:
      - Software Architektur: 'moodle/software-architektur.md'
      - Admin Tool: 'moodle/admin-tool.md'
      - Repository: 'moodle/repository.md'
      - Collaborative Folders: 'moodle/activity.md'
    - Benutzung: 'moodle/benutzung.md'
