# Project information
site_name: 'sciebo@Learnweb'
site_author: 'Lukas Biermann, Nina Herrmann, Wladislaw Iwanzow, Dennis Meis, Jonathan Neugebauer'
repo_url: "https://github.com/pssl16"

# Copyright
copyright: 'Copyright &copy; 2017 PSSL16'

# Documentation and theme
docs_dir: 'docs'
theme_dir: 'cinder'

pages:
  - Home: 'index.md'
  - ownCloud:
    - Technische Umsetzung:
      - Softwarearchitektur: 'owncloud/technische-umsetzung/softwarearchitektur.md'
      - OAuth 2.0 App: 'owncloud/technische-umsetzung/oauth2-app.md'
      - Core Anpassungen: 'owncloud/technische-umsetzung/core-anpassungen.md'
    - Benutzung: 'owncloud/benutzung.md'
  - Moodle:
    - Technische Umsetzung:
      - Softwarearchitektur: 'moodle/technische-umsetzung/softwarearchitektur.md'
      - Admin Tool: 'moodle/technische-umsetzung/admin-tool.md'
      - Repository: 'moodle/technische-umsetzung/repository.md'
      - Collaborative Folders: 'moodle/technische-umsetzung/activity.md'
    - Benutzung: 'moodle/benutzung.md'
